

# # explainer_50_nodes_non_iid_DP_BB
# poetry run python /home/lcorbucci/private_fastshap/FL/FL/examples/income_explainer_reduced/../../main.py --batch_size=418 --eff_lambda=0.0660451592490019 --epochs=5 --lr=0.004856975632635676 --num_samples=47 --optimizer=adam --paired_sampling=False --validation_samples=27 --dataset_name income --fl_rounds 10 --num_client_cpus 1 --num_client_gpus 0.1 --tabular True --num_nodes 50 --sampled_training_nodes 0.225 --sampled_validation_nodes 0 --sampled_test_nodes 1 --dataset_path /raid/lcorbucci/folktables/income_data_reduced --seed 42 --wandb True --split_approach non_iid --fraction_fit_nodes 0.8 --fraction_validation_nodes 0 --fraction_test_nodes 0.2 --device cuda --cross_device True --split_approach non_iid --alpha_dirichlet 5 --train_explainer True --surrogate_name ./surrogate_DP_1_reduced.pth --save_aggregated_model True --aggregated_model_name explainer_NO_DP

# # explainer_50_nodes_non_iid_DP_05_DP_BB
# poetry run python /home/lcorbucci/private_fastshap/FL/FL/examples/income_explainer_reduced/../../main.py --batch_size=277 --clipping=1.3394659881423774 --eff_lambda=0.13504202567297452 --epochs=7 --lr=0.001401001232349134 --num_samples=29 --optimizer=adam --paired_sampling=False --validation_samples=22 --dataset_name income --fl_rounds 10 --num_client_cpus 1 --num_client_gpus 0.1 --tabular True --num_nodes 50 --sampled_training_nodes 0.225 --sampled_validation_nodes 0 --sampled_test_nodes 1 --dataset_path /raid/lcorbucci/folktables/income_data_reduced --seed 42 --wandb True --split_approach non_iid --fraction_fit_nodes 0.8 --fraction_validation_nodes 0 --fraction_test_nodes 0.2 --device cuda --cross_device True --split_approach non_iid --alpha_dirichlet 5 --train_explainer True --surrogate_name ./surrogate_DP_1_reduced.pth --epsilon 0.5 --save_aggregated_model True --aggregated_model_name explainer_DP_05

# # explainer_50_nodes_non_iid_DP_2_DP_BB
# poetry run python /home/lcorbucci/private_fastshap/FL/FL/examples/income_explainer_reduced/../../main.py --batch_size=272 --clipping=12.7329142512157 --eff_lambda=0.8992254158868159 --epochs=7 --lr=0.0035826449064073726 --num_samples=36 --optimizer=adam --paired_sampling=False --validation_samples=24 --dataset_name income --fl_rounds 10 --num_client_cpus 1 --num_client_gpus 0.1 --tabular True --num_nodes 50 --sampled_training_nodes 0.225 --sampled_validation_nodes 0 --sampled_test_nodes 1 --dataset_path /raid/lcorbucci/folktables/income_data_reduced --seed 42 --wandb True --split_approach non_iid --fraction_fit_nodes 0.8 --fraction_validation_nodes 0 --fraction_test_nodes 0.2 --device cuda --cross_device True --split_approach non_iid --alpha_dirichlet 5 --train_explainer True --surrogate_name ./surrogate_DP_1_reduced.pth --epsilon 2  --save_aggregated_model True --aggregated_model_name explainer_DP_2



# # explainer_50_nodes_non_iid_DP_2_DP_BB
# poetry run python /home/lcorbucci/private_fastshap/FL/FL/examples/income_explainer_reduced/../../main.py --batch_size=479 --clipping=2.494834536718963 --eff_lambda=0.9149164533125416 --epochs=10 --lr=0.003600400480554332 --num_samples=25 --optimizer=adam --paired_sampling=False --validation_samples=21 --dataset_name income --fl_rounds 10 --num_client_cpus 1 --num_client_gpus 0.1 --tabular True --num_nodes 50 --sampled_training_nodes 0.225 --sampled_validation_nodes 0 --sampled_test_nodes 1 --dataset_path /raid/lcorbucci/folktables/income_data_reduced --seed 42 --wandb True --split_approach non_iid --fraction_fit_nodes 0.8 --fraction_validation_nodes 0 --fraction_test_nodes 0.2 --device cuda --cross_device True --split_approach non_iid --alpha_dirichlet 5 --train_explainer True --surrogate_name ./surrogate_DP_1_reduced.pth --epsilon 2  --save_aggregated_model True --aggregated_model_name explainer_DP_2

# # explainer_50_nodes_non_iid_DP_5_DP_BB
# poetry run python /home/lcorbucci/private_fastshap/FL/FL/examples/income_explainer_reduced/../../main.py --batch_size=502 --clipping=4.284541785889911 --eff_lambda=0.005224534570164141 --epochs=5 --lr=0.001444458257316176 --num_samples=35 --optimizer=adam --paired_sampling=True --validation_samples=24 --dataset_name income --fl_rounds 10 --num_client_cpus 1 --num_client_gpus 0.1 --tabular True --num_nodes 50 --sampled_training_nodes 0.225 --sampled_validation_nodes 0 --sampled_test_nodes 1 --dataset_path /raid/lcorbucci/folktables/income_data_reduced --seed 42 --wandb True --split_approach non_iid --fraction_fit_nodes 0.8 --fraction_validation_nodes 0 --fraction_test_nodes 0.2 --device cuda --cross_device True --split_approach non_iid --alpha_dirichlet 5 --train_explainer True --surrogate_name ./surrogate_DP_1_reduced.pth --epsilon 5 --splitted_data_dir federated_2  --save_aggregated_model True --aggregated_model_name explainer_DP_5


# dutch_explainer_50_nodes_non_iid_DP_5_DP_BB
# poetry run python /home/lcorbucci/private_fastshap/FL/FL/examples/dutch_explainer/../../main.py --batch_size=364 --clipping=3.980830585413371 --eff_lambda=0.06388493515796323 --epochs=10 --lr=0.0037460742767675935 --optimizer=adam --paired_sampling=True --validation_batch_size=9740 --validation_samples=6 --dataset_name dutch --fl_rounds 10 --num_client_cpus 1 --num_client_gpus 0.1 --tabular True --num_nodes 50 --sampled_training_nodes 0.225 --sampled_validation_nodes 0 --sampled_test_nodes 0 --dataset_path ../../../../data/dutch/ --seed 42 --wandb True --split_approach non_iid --fraction_fit_nodes 0.8 --fraction_validation_nodes 0 --fraction_test_nodes 0.2 --device cuda --cross_device True --split_approach non_iid --alpha_dirichlet 5 --train_explainer True --surrogate_name ./dutch_surrogate_DP_1.pth --epsilon 5 --save_aggregated_model True --aggregated_model_name explainer_DP_5


poetry run python /home/lcorbucci/private_fastshap/FL/FL/examples/income_explainer_reduced/../../main.py --batch_size=424 --eff_lambda=0.4431242415255253 --epochs=5 --lr=0.017879318332587702 --num_samples=45 --optimizer=adam --paired_sampling=True --validation_samples=48 --dataset_name income --fl_rounds 10 --num_client_cpus 1 --num_client_gpus 0.1 --tabular True --num_nodes 50 --sampled_training_nodes 0.225 --sampled_validation_nodes 0 --sampled_test_nodes 1 --dataset_path /raid/lcorbucci/folktables/income_data_reduced --seed 42 --wandb True --split_approach non_iid --fraction_fit_nodes 0.8 --fraction_validation_nodes 0 --fraction_test_nodes 0.2 --device cuda --cross_device True --split_approach non_iid --alpha_dirichlet 5 --train_explainer True --surrogate_name ./surrogate_NO_DP.pth  --save_aggregated_model True --aggregated_model_name explainer_confronto