
# explainer_50_nodes_non_iid_DP_1_DP_BB
poetry run python /home/lcorbucci/private_fastshap/FL/FL/examples/income_explainer_reduced/../../main.py --batch_size=304 --clipping=2.44245202440788 --eff_lambda=0.016843245445491983 --epochs=9 --lr=0.01471898586657231 --num_samples=18 --optimizer=sgd --paired_sampling=False --validation_samples=18 --dataset_name income --fl_rounds 10 --num_client_cpus 1 --num_client_gpus 0.1 --tabular True --num_nodes 50 --sampled_training_nodes 0.225 --sampled_validation_nodes 0 --sampled_test_nodes 1 --dataset_path /raid/lcorbucci/folktables/income_data_reduced --seed 42 --wandb True --split_approach non_iid --fraction_fit_nodes 0.8 --fraction_validation_nodes 0 --fraction_test_nodes 0.2 --device cuda --cross_device True --split_approach non_iid --alpha_dirichlet 5 --train_explainer True --surrogate_name ./surrogate_DP_1_reduced.pth --epsilon 1 --splitted_data_dir federated_2 --save_aggregated_model True --aggregated_model_name explainer_DP_1

# explainer_50_nodes_non_iid_DP_01_DP_BB
poetry run python /home/lcorbucci/private_fastshap/FL/FL/examples/income_explainer_reduced/../../main.py --batch_size=487 --clipping=1.6087231410357647 --eff_lambda=0.33300915968427125 --epochs=8 --lr=0.0111244553598013 --num_samples=24 --optimizer=sgd --paired_sampling=True --validation_samples=39 --dataset_name income --fl_rounds 10 --num_client_cpus 1 --num_client_gpus 0.1 --tabular True --num_nodes 50 --sampled_training_nodes 0.225 --sampled_validation_nodes 0 --sampled_test_nodes 1 --dataset_path /raid/lcorbucci/folktables/income_data_reduced --seed 42 --wandb True --split_approach non_iid --fraction_fit_nodes 0.8 --fraction_validation_nodes 0 --fraction_test_nodes 0.2 --device cuda --cross_device True --split_approach non_iid --alpha_dirichlet 5 --train_explainer True --surrogate_name ./surrogate_DP_1_reduced.pth --epsilon 0.1 --splitted_data_dir federated_2 --save_aggregated_model True --aggregated_model_name explainer_DP_01

# explainer_50_nodes_non_iid_DP_5_DP_BB
poetry run python /home/lcorbucci/private_fastshap/FL/FL/examples/income_explainer_reduced/../../main.py --batch_size=264 --clipping=7.457261513003545 --eff_lambda=0.6344040610269944 --epochs=10 --lr=0.00826225463614131 --num_samples=28 --optimizer=sgd --paired_sampling=True --validation_samples=19 --dataset_name income --fl_rounds 10 --num_client_cpus 1 --num_client_gpus 0.1 --tabular True --num_nodes 50 --sampled_training_nodes 0.225 --sampled_validation_nodes 0 --sampled_test_nodes 1 --dataset_path /raid/lcorbucci/folktables/income_data_reduced --seed 42 --wandb True --split_approach non_iid --fraction_fit_nodes 0.8 --fraction_validation_nodes 0 --fraction_test_nodes 0.2 --device cuda --cross_device True --split_approach non_iid --alpha_dirichlet 5 --train_explainer True --surrogate_name ./surrogate_DP_1_reduced.pth --epsilon 5 --splitted_data_dir federated_2 --save_aggregated_model True --aggregated_model_name explainer_DP_5
