# # NO DP
poetry run python /home/lcorbucci/private_fastshap/FL/FL/examples/dutch_explainer/../../main.py --batch_size=45 --eff_lambda=0.24452951689098057 --epochs=9 --lr=0.001804512062345966 --optimizer=adam --paired_sampling=True --validation_batch_size=1807 --validation_samples=9 --dataset_name dutch --fl_rounds 10 --num_client_cpus 1 --num_client_gpus 0.1 --tabular True --num_nodes 50 --sampled_training_nodes 0.225 --sampled_validation_nodes 0 --sampled_test_nodes 1 --dataset_path ../../../../data/dutch/ --seed 42 --wandb True --split_approach non_iid --fraction_fit_nodes 0.8 --fraction_validation_nodes 0 --fraction_test_nodes 0.2 --device cuda --cross_device True --split_approach non_iid --alpha_dirichlet 5 --train_explainer True --surrogate_name ./dutch_surrogate_NO_DP.pth --save_aggregated_model True --aggregated_model_name NO_DP

# # DP 0.1
poetry run python /home/lcorbucci/private_fastshap/FL/FL/examples/dutch_explainer/../../main.py --batch_size=96 --clipping=3.57152084477682 --eff_lambda=0.6210426624025707 --epochs=5 --lr=0.004471324604175378 --optimizer=adam --paired_sampling=True --validation_batch_size=3615 --validation_samples=5 --dataset_name dutch --fl_rounds 10 --num_client_cpus 1 --num_client_gpus 0.1 --tabular True --num_nodes 50 --sampled_training_nodes 0.225 --sampled_validation_nodes 0 --sampled_test_nodes 1 --dataset_path ../../../../data/dutch/ --seed 42 --wandb True --split_approach non_iid --fraction_fit_nodes 0.8 --fraction_validation_nodes 0 --fraction_test_nodes 0.2 --device cuda --cross_device True --split_approach non_iid --alpha_dirichlet 5 --train_explainer True --surrogate_name ./dutch_surrogate_NO_DP.pth --save_aggregated_model True --epsilon 0.1 --aggregated_model_name DP_01

# # DP 0.5 
poetry run python /home/lcorbucci/private_fastshap/FL/FL/examples/dutch_explainer/../../main.py --batch_size=178 --clipping=2.8200260279177543 --eff_lambda=0.08582759326936518 --epochs=8 --lr=0.03580082062740948 --optimizer=sgd --paired_sampling=True --validation_batch_size=3453 --validation_samples=6 --dataset_name dutch --fl_rounds 10 --num_client_cpus 1 --num_client_gpus 0.1 --tabular True --num_nodes 50 --sampled_training_nodes 0.225 --sampled_validation_nodes 0 --sampled_test_nodes 1 --dataset_path ../../../../data/dutch/ --seed 42 --wandb True --split_approach non_iid --fraction_fit_nodes 0.8 --fraction_validation_nodes 0 --fraction_test_nodes 0.2 --device cuda --cross_device True --split_approach non_iid --alpha_dirichlet 5 --train_explainer True --surrogate_name ./dutch_surrogate_NO_DP.pth --epsilon 0.5 --aggregated_model_name DP_05 --save_aggregated_model True


# # DP 1
poetry run python /home/lcorbucci/private_fastshap/FL/FL/examples/dutch_explainer/../../main.py --batch_size=216 --clipping=7.091967637167231 --eff_lambda=0.8981587162790137 --epochs=6 --lr=0.011643008025487737 --optimizer=adam --paired_sampling=False --validation_batch_size=9883 --validation_samples=10 --dataset_name dutch --fl_rounds 10 --num_client_cpus 1 --num_client_gpus 0.1 --tabular True --num_nodes 50 --sampled_training_nodes 0.225 --sampled_validation_nodes 0 --sampled_test_nodes 1 --dataset_path ../../../../data/dutch/ --seed 42 --wandb True --split_approach non_iid --fraction_fit_nodes 0.8 --fraction_validation_nodes 0 --fraction_test_nodes 0.2 --device cuda --cross_device True --split_approach non_iid --alpha_dirichlet 5 --train_explainer True --surrogate_name ./dutch_surrogate_NO_DP.pth --epsilon 1 --aggregated_model_name DP_1 --save_aggregated_model True


# # DP 2
poetry run python /home/lcorbucci/private_fastshap/FL/FL/examples/dutch_explainer/../../main.py --batch_size=319 --clipping=2.989459511787087 --eff_lambda=0.1607558036629131 --epochs=10 --lr=0.01175068476211286 --optimizer=adam --paired_sampling=False --validation_batch_size=5435 --validation_samples=9 --dataset_name dutch --fl_rounds 10 --num_client_cpus 1 --num_client_gpus 0.1 --tabular True --num_nodes 50 --sampled_training_nodes 0.225 --sampled_validation_nodes 0 --sampled_test_nodes 1 --dataset_path ../../../../data/dutch/ --seed 42 --wandb True --split_approach non_iid --fraction_fit_nodes 0.8 --fraction_validation_nodes 0 --fraction_test_nodes 0.2 --device cuda --cross_device True --split_approach non_iid --alpha_dirichlet 5 --train_explainer True --surrogate_name ./dutch_surrogate_NO_DP.pth --epsilon 2 --aggregated_model_name DP_2 --save_aggregated_model True

# # DP 1000
poetry run python /home/lcorbucci/private_fastshap/FL/FL/examples/dutch_explainer/../../main.py --batch_size=266 --clipping=1.0482638130468722 --eff_lambda=0.8690339162921209 --epochs=9 --lr=0.00876000521550753 --optimizer=adam --paired_sampling=True --validation_batch_size=5761 --validation_samples=10 --dataset_name dutch --fl_rounds 10 --num_client_cpus 1 --num_client_gpus 0.1 --tabular True --num_nodes 50 --sampled_training_nodes 0.225 --sampled_validation_nodes 0 --sampled_test_nodes 1 --dataset_path ../../../../data/dutch/ --seed 42 --wandb True --split_approach non_iid --fraction_fit_nodes 0.8 --fraction_validation_nodes 0 --fraction_test_nodes 0.2 --device cuda --cross_device True --split_approach non_iid --alpha_dirichlet 5 --train_explainer True --surrogate_name ./dutch_surrogate_NO_DP.pth --epsilon 1000 --aggregated_model_name DP_1000 --save_aggregated_model True